'(org-level-1 ((t (:bold t :foreground "dodger blue" :height 1.5))))
'(org-level-2 ((t (:bold t :foreground "#edd400" :height 1.2))))
'(org-level-3 ((t (:bold t :foreground "#6ac214" :height 1.0))))
'(org-level-4 ((t (:bold nil :foreground "tomato" :height 1.0))))
'(org-date ((t (:underline t :foreground "magenta3"))))
'(org-footnote  ((t (:underline t :foreground "magenta3"))))
'(org-link ((t (:foreground "skyblue2" :background "#2e3436" :underline nil))))
'(org-special-keyword ((t (:foreground "brown"))))
'(org-verbatim ((t (:foreground "#eeeeec" :underline t :slant italic))))
'(org-block ((t (:foreground "#bbbbbc"))))
'(org-quote ((t (:inherit org-block :slant italic))))
'(org-verse ((t (:inherit org-block :slant italic))))
'(org-todo ((t (:bold t :foreground "Red"))))
'(org-done ((t (:bold t :foreground "ForestGreen"))))
'(org-agenda-structure ((t (:weight bold :foreground "tomato"))))
'(org-agenda-date ((t (:foreground "#6ac214"))))
'(org-agenda-date-weekend ((t (:weight normal :foreground "dodger blue"))))
'(org-agenda-date-today ((t (:weight bold :foreground "#edd400"))))
'(org-scheduled-previously ((t (:weight normal :foreground "#edd400"))))
'(org-block-begin-line ((t ( :foreground "#888a85" :background "#252b2b"))))
'(org-block-background ((t (:background "#252b2b"))))
'(org-block-end-line ((t ( :foreground "#888a85" :background "#252b2b"))))

(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)
   (haskell . t)
   (python . t)
   (ruby . t)))

(setq org-confirm-babel-evaluate nil)
(setq org-src-fontify-natively t)
