require("config.compe")
require("config.devicons")
require("config.formatter")
require("config.gitsigns")
require("config.lspconfig")
require("config.lspkind")
require("config.startify")
require("config.treesitter")

require("colorizer").setup()
require("trouble").setup({})
