-- require("nvim-treesitter.configs").setup {
--   ensure_installed = {
--     "c",
--     "css",
--     "erlang",
--     "json",
--     "lua",
--     "ruby",
--     "rust",
--     "toml",
--     "tsx",
--     "typescript",
--     "yaml",
--   },

--   highlight = {
--     enable = true,
--   },

--   incremental_selection = {
--     enable = true,
--     keymaps = {
--       init_selection = "gnn",
--       node_incremental = "grn",
--       scope_incremental = "grc",
--       node_decremental = "grm",
--     },
--   },

--   indent = {
--     enable = false,
--   },
-- }
