# This file is sourced by login shells during logout.
# It should be used for displaying messages and the deletion of files.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Nicholas Scheurich <nick@scheurich.me>

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {
