export BROWSER='open'

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

typeset -gU cdpath fpath mailpath path

if [[ -f /usr/libexec/path_helper ]]; then
  eval "$(/usr/libexec/path_helper -s)"
fi

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:/usr/local/bin:/usr/local/sbin:/usr/bin/core_perl"
export PATH="$PATH:/usr/local/opt/go/libexec/bin"
export PATH="$PATH:/Applications/PICO-8/PICO-8.app/Contents/MacOS"
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:/usr/local/opt/openssl/bin"

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
