# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   N. G. Scheurich <nick@scheurich.me>
#
# URL: https://github.com/ngscheurich/dotfiles

# ------------------------------------------------------------------------------
# Setup
# ------------------------------------------------------------------------------
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

eval "$(fasd --init auto)"
eval "$(starship init zsh)"
eval "$(thefuck --alias)"

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ------------------------------------------------------------------------------
# Options
# ------------------------------------------------------------------------------
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_DUPS
setopt INC_APPEND_HISTORY

# ------------------------------------------------------------------------------
# Aliases
# ------------------------------------------------------------------------------
alias curlh="curl -s -D - -o /dev/null"
alias giga="gigalixir"
alias git="hub"
alias http="python -m http.server"
alias lg="lazygit"
alias vimconfig="$EDITOR $HOME/.vimrc"
alias vimdiff="vim -d"
alias vboxls="VBoxManage list runningvms"
alias weather="curl wttr.in/Baton+Rouge"
alias zshconfig="$EDITOR $HOME/.zshrc"
alias zshsource="source $HOME/.zshrc"

# Load gem man pages
alias man="gem man -ls"

# ------------------------------------------------------------------------------
# Keybinds
# ------------------------------------------------------------------------------
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line

eval "$(direnv hook zsh)"

